### ISSUE TITLE
oauth_token

### ISSUE THREAD

**Issue by isomorphisms** [valeriangalliat/twdump#1]
```
./twdump \
    --consumer-key "$consumer_key" \
    --consumer-secret "$consumer_key" \
    --oauth-token "$consumer_token" \
    --oauth-key "$consumer_key" \
    youraccount
```

do you mean `access-token` and `access-secret`?  Also you reused `$consumer_key` three times, is that on purpose?

**Comment by valeriangalliat** [comment]
Ha, good catch, it was a mistake when writing the documentation. I updated the readme, it's indeed 4 different variables.

**Comment by isomorphisms** [comment]
thanks @valeriangalliat !

**Comment by isomorphisms** [comment]
it's a very nice package, thank you :)
